const Data=[
    {
        id:1,
        img:"https://media.istockphoto.com/id/1925865357/photo/apartment-buildings-austin-texas.webp?a=1&b=1&s=612x612&w=0&k=20&c=sJNCRaHUI5NG_2LA1e1tJD3W33QoGYFcHTRImTf0CpE=",
        title:"South City Garden",
        desc:"3 BHK flat in South City Garden",
        agent:"Subham Gill",
        bedrooms:3,
        price:120000,
        amenity:["Park","Lift"],
        location:"kolkata",
        bhk:3,
        area:838,
        date:"12-09-2024"
    },
    {
        id: 2,
        img:"https://media.istockphoto.com/id/2076934092/photo/apartment-building-with-autumn-trees-landscape.webp?a=1&b=1&s=612x612&w=0&k=20&c=X8qclT0IkDiCHyiVBRF0blEKheddt2K_Fdc08_HnTrE=",
        title: "Greenwood Residency",
        desc: "2 BHK flat in Greenwood Residency",
        agent: "Rohit Verma",
        bedrooms: 2,
        price: 85000,
        amenity: ["Gym", "Swimming Pool"],
        location: "Mumbai",
        bhk: 2,
        area: 720,
        date: "15-09-2024"
    },
    {
        id: 3,
        img:"https://media.istockphoto.com/id/1440568749/photo/modern-apartment-buildings-in-the-evening.webp?a=1&b=1&s=612x612&w=0&k=20&c=EYdMWmiSmxQXoWaRdxpqEBTOPWzLKiqlWK3b_prexOQ=",
        title: "Sunrise Apartments",
        desc: "1 BHK flat in Sunrise Apartments",
        agent: "Pooja Singh",
        bedrooms: 1,
        price: 60000,
        amenity: ["Lift", "Parking"],
        location: "Pune",
        bhk: 1,
        area: 550,
        date: "18-09-2024"
    },
    {
        id: 4,
        img: "https://images.unsplash.com/photo-1578055384140-5d8a31f5833f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmxhdHN8ZW58MHx8MHx8fDA%3D",
        title: "Heights Residency",
        desc: "4 BHK flat in Heights Residency",
        agent: "Amit Roy",
        bedrooms: 4,
        price: 175000,
        amenity: ["Club House", "Park"],
        location: "Chennai",
        bhk: 4,
        area: 1100,
        date: "20-09-2024"
    },
    {
        id: 5,
        img: "https://plus.unsplash.com/premium_photo-1671196048754-03a77d051dcb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZmxhdHN8ZW58MHx8MHx8fDA%3D",
        title: "Blue Horizon",
        desc: "3 BHK flat in Blue Horizon",
        agent: "Manish Sharma",
        bedrooms: 3,
        price: 130000,
        amenity: ["Swimming Pool", "Security"],
        location: "Bangalore",
        bhk: 3,
        area: 890,
        date: "25-09-2024"
    },
    {
        id: 6,
        img: "https://plus.unsplash.com/premium_photo-1664267475555-d0f774fc534a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGZsYXRzfGVufDB8fDB8fHww",
        title: "Orchid Residency",
        desc: "2 BHK flat in Orchid Residency",
        agent: "Neha Gupta",
        bedrooms: 2,
        price: 92000,
        amenity: ["Gym", "Lift"],
        location: "Delhi",
        bhk: 2,
        area: 750,
        date: "28-09-2024"
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1444750023/photo/high-rise-apartments-or-building-luxury-apartments-or-building-society.jpg?s=612x612&w=0&k=20&c=D0Dy3KSe3-Ttptk0wZP1ivwmdVz7byePIbfqjnUJhEE=",
        title: "Maple Woods",
        desc: "3 BHK flat in Maple Woods",
        agent: "Vikas Tiwari",
        bedrooms: 3,
        price: 140000,
        amenity: ["Park", "Parking"],
        location: "Hyderabad",
        bhk: 3,
        area: 870,
        date: "30-09-2024"
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1223059837/photo/cityscape-of-a-modern-residential-area-with-apartment-buildings-new-green-urban-landscape-in.jpg?s=612x612&w=0&k=20&c=UWmzWnHmiLmBF32B6KaNl9acntTWGFrZgjidWat8UXo=",
        title: "Silver Crest",
        desc: "2 BHK flat in Silver Crest",
        agent: "Ankita Bose",
        bedrooms: 2,
        price: 78000,
        amenity: ["Club House", "Gym"],
        location: "Jaipur",
        bhk: 2,
        area: 670,
        date: "02-10-2024"
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1357037904/photo/night-scene-modern-living-room-with-metropolis-view-background-3d-render.jpg?s=612x612&w=0&k=20&c=yEgNdJTppFayIiiXyiCLGLH9g9Ro6Oiv2DLUxUduS5w=",
        title: "Royal Palms",
        desc: "4 BHK flat in Royal Palms",
        agent: "Nitin Malhotra",
        bedrooms: 4,
        price: 180000,
        amenity: ["Security", "Lift"],
        location: "Ahmedabad",
        bhk: 4,
        area: 1150,
        date: "05-10-2024"
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/1346322259/photo/sunset-during-pandemic-in-gurgaon-city-urban-skyline-on-september-04-delhi-ncrs.jpg?s=612x612&w=0&k=20&c=QirxFxVrDO-2XclqRcwIYx6CpG0ocNeqDStFmynbtRw=",
        title: "Emerald Greens",
        desc: "3 BHK flat in Emerald Greens",
        agent: "Priya Sen",
        bedrooms: 3,
        price: 125000,
        amenity: ["Park", "Swimming Pool"],
        location: "Kolkata",
        bhk: 3,
        area: 850,
        date: "07-10-2024"
    }
]

export default Data