const Data=[
    {
        id:1,
        img:"https://media.istockphoto.com/id/1925865357/photo/apartment-buildings-austin-texas.webp?a=1&b=1&s=612x612&w=0&k=20&c=sJNCRaHUI5NG_2LA1e1tJD3W33QoGYFcHTRImTf0CpE=",
        title:"South City Garden",
        desc:"3 BHK flat in South City Garden",
        agent:"Subham Gill",
        bedrooms:3,
        price:120000,
        amenity:["Park","Lift"],
        location:"kolkata",
        bhk:3,
        area:838,
        date:"12-09-2024"
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1848310587/photo/luxury-apartments-in-downtown.webp?a=2&b=2&s=612x612&w=0&k=20&c=Oc6f95y2MR5XpMYckFdVleT2IgAQOxv6keYzFZQyguU=",
        title: "Greenwood Residency",
        desc: "2 BHK flat in Greenwood Residency",
        agent: "Rohit Verma",
        bedrooms: 2,
        price: 85000,
        amenity: ["Gym", "Swimming Pool"],
        location: "Mumbai",
        bhk: 2,
        area: 720,
        date: "15-09-2024"
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1757458177/photo/apartment-building-in-downtown.webp?a=3&b=3&s=612x612&w=0&k=20&c=wB_z0DWWKK2QpM7Yqug1_W9kWVaLsWSQ2IfHsP4NybM=",
        title: "Sunrise Apartments",
        desc: "1 BHK flat in Sunrise Apartments",
        agent: "Pooja Singh",
        bedrooms: 1,
        price: 60000,
        amenity: ["Lift", "Parking"],
        location: "Pune",
        bhk: 1,
        area: 550,
        date: "18-09-2024"
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1951253065/photo/modern-apartment-buildings-at-night.webp?a=4&b=4&s=612x612&w=0&k=20&c=kgfDd6aSvUEqdzT9egFMnmyMDvzoGHlkEr6t5TlIW58=",
        title: "Heights Residency",
        desc: "4 BHK flat in Heights Residency",
        agent: "Amit Roy",
        bedrooms: 4,
        price: 175000,
        amenity: ["Club House", "Park"],
        location: "Chennai",
        bhk: 4,
        area: 1100,
        date: "20-09-2024"
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1830320216/photo/modern-apartment-building-in-the-evening.webp?a=5&b=5&s=612x612&w=0&k=20&c=70i4cfyL4KxAjZ9yDGSIDTOBwYsQPiHf20FvlbFGnoM=",
        title: "Blue Horizon",
        desc: "3 BHK flat in Blue Horizon",
        agent: "Manish Sharma",
        bedrooms: 3,
        price: 130000,
        amenity: ["Swimming Pool", "Security"],
        location: "Bangalore",
        bhk: 3,
        area: 890,
        date: "25-09-2024"
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1845377036/photo/luxury-apartments-in-sunset.webp?a=6&b=6&s=612x612&w=0&k=20&c=YrMhPqaWYFw8lLCp_5_h1Yp7TQc_sTx_izboOXCG9Qo=",
        title: "Orchid Residency",
        desc: "2 BHK flat in Orchid Residency",
        agent: "Neha Gupta",
        bedrooms: 2,
        price: 92000,
        amenity: ["Gym", "Lift"],
        location: "Delhi",
        bhk: 2,
        area: 750,
        date: "28-09-2024"
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1963871736/photo/modern-apartment-buildings-at-dusk.webp?a=7&b=7&s=612x612&w=0&k=20&c=Fh7bEZjT3DZcnAYrC2L14el3zwuFVkCBqiFyoN5FS24=",
        title: "Maple Woods",
        desc: "3 BHK flat in Maple Woods",
        agent: "Vikas Tiwari",
        bedrooms: 3,
        price: 140000,
        amenity: ["Park", "Parking"],
        location: "Hyderabad",
        bhk: 3,
        area: 870,
        date: "30-09-2024"
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1925865357/photo/apartment-buildings-in-dusk.webp?a=8&b=8&s=612x612&w=0&k=20&c=xNFOquSMYiD0M2X7yT5FZdpJHNsO_nJ0lhz5fnRTsM4=",
        title: "Silver Crest",
        desc: "2 BHK flat in Silver Crest",
        agent: "Ankita Bose",
        bedrooms: 2,
        price: 78000,
        amenity: ["Club House", "Gym"],
        location: "Jaipur",
        bhk: 2,
        area: 670,
        date: "02-10-2024"
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1925865357/photo/new-residential-apartment-buildings.webp?a=9&b=9&s=612x612&w=0&k=20&c=ILlCTwRDb09AqFfbFpijVx4lXBltDbr6oG2wZbDwuyE=",
        title: "Royal Palms",
        desc: "4 BHK flat in Royal Palms",
        agent: "Nitin Malhotra",
        bedrooms: 4,
        price: 180000,
        amenity: ["Security", "Lift"],
        location: "Ahmedabad",
        bhk: 4,
        area: 1150,
        date: "05-10-2024"
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/1913024179/photo/modern-apartment-buildings-in-city.webp?a=10&b=10&s=612x612&w=0&k=20&c=ES_aA7W_jrAVS_W7BoFNDflAcdbUj4MYcWqTk-JmIx4=",
        title: "Emerald Greens",
        desc: "3 BHK flat in Emerald Greens",
        agent: "Priya Sen",
        bedrooms: 3,
        price: 125000,
        amenity: ["Park", "Swimming Pool"],
        location: "Kolkata",
        bhk: 3,
        area: 850,
        date: "07-10-2024"
    }
]

export default Data